dataset_params:
  dataset_name: CIFAR10
  forget_sets:
    - 'random'
    - 'random'
    - 'random'
    - 'random'
    - 'random'
    - 'random'
    - 'random'
    - 'random'
    - 'random'
  forget_set_size: 
    - 3
    - 6
    - 30
    - 60
    - 300
    - 600
    - 3000
    - 6000
    - 15000
distinguisher_params:
  mia:
    mia_type: logreg
  mse: null
  kld:
    perturbation_type: gaussian
unlearning_methods:
  certified_removal: 
    lambda: 0.25
    sigma: 2
    # epsilon: 1.e-1
    # delta: 1.e-2
batch_size: 512
train_params:
  num_epochs: 40
  learning_rate: 0.01
  use_differential_privacy: True
  use_certified_removal: True
  epsilon: 1.e-1
  delta: 1.e-2
  max_physical_batch_size: 128
  num_workers: 0
runs_per_forget_set: 1
