dataset_params:
  dataset_name: CIFAR10
  forget_sets:
    - 'random'
    - 'random'
    - 'random'
    - 'random'
    - 'random'
    - 'random'
    - 'random'
  forget_set_size: 
    - 3
    - 6
    - 30
    - 60
    - 300
    - 600
    - 3000
distinguisher_params:
  mia:
    mia_type: logreg
  mse: null
  kld:
    perturbation_type: gaussian
unlearning_methods:
  certified_deep_unlearning: 
    weight_decay: 5.e-4
    s1: 10
    s2: 1000
    gamma: 2000
    scale: 50000
    std: 1.e-3
batch_size: 1024
train_params:
  num_epochs: 50
  learning_rate: 1.e-2
  num_workers: 16
  use_param_norm: True
  max_norm: 20
  pretrained: False
runs_per_experiment: 128
