dataset_params:
  dataset_name: MNIST
  forget_sets:
    - 'random'
    - 'random'
  forget_set_size: 
    - 1000
    - 15000
distinguisher_params:
  mia:
    mia_type: logreg
  mse: null
  kld:
    perturbation_type: gaussian
unlearning_methods:
  certified_deep_unlearning: 
    weight_decay: 5.e-4
    s1: 10
    s2: 3
    gamma: 2000
    scale: 50000
    std: 1.e-3
batch_size: 512
train_params:
  num_epochs: 3
  learning_rate: 1.e-3
  num_workers: 0
  use_param_norm: True
  max_norm: 20
  pretrained: False
runs_per_forget_set: 1
