name: unlearning
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - scikit-learn
  - pandas
  - torchaudio
  - plotly
  - matplotlib
  - wandb
  - tqdm
  - torchvision
  - python
  - pip
  - pytorch-cuda=12.1
  - pytorch
  - opacus
  - pip:
    - kaleido==0.2.1
    - seaborn==0.13.2
# prefix: /fast/mathepa1/anaconda3/envs/unlearning
