name: unlearning
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - torchvision
  - pandas
  - pytorch-cuda=12.1
  - plotly
  - tqdm
  - torchaudio
  - matplotlib
  - seaborn
  - scikit-learn
  - wandb
