dataset_params:
  dataset_name: CIFAR10
  forget_sets:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - 'random'
  forget_set_size: 7000 # Only used for random forgets set
distinguisher_params:
  mia:
    mia_type: logreg
  kld: 
    perturbation_type: gaussian
unlearning_methods:
  ssd:
    dampening_constant: 1
    selection_weighting: 5
batch_size: 256
train_params:
  num_epochs: 200
  learning_rate: 0.1
