dataset_params:
  dataset_name: MNIST
  forget_sets:
    - '0'
    - '1'
  forget_set_size: 7000 # Only used for random forget sets
distinguisher_params:
  mia:
    mia_type: logreg
  kld: 
    perturbation_type: gaussian
  mse: null
unlearning_methods:
  ssd:
    dampening_constant: 1
    selection_weighting: 10
  # fisher_forgetting: null
  # amnesiac: null
batch_size: 256
train_params:
  num_epochs: 2
  learning_rate: 1.e-3
