dataset_params:
  dataset_name: CIFAR10
  forget_sets:
    - 'random'
    - 'random'
  forget_set_size: 
    - 30
    - 60
distinguisher_params:
  mia:
    mia_type: logreg
  kld: 
    perturbation_type: gaussian
  mse: null
unlearning_methods:
  dp_sgd:
    eps: 1.e-3
    delta: 1.e-3
    lr: 1.e-3

batch_size: 256
train_params:
  num_epochs: 200
  learning_rate: 0.1
  norm_layer: norm
  use_differential_privacy: True
runs_per_forget_set: 1
