dataset_params:
  dataset_name: MNIST
  forget_sets:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
  forget_set_size: 7000 # Only used for random forget sets
distinguisher_params:
  mia:
    mia_type: logreg
  kld: 
    perturbation_type: gaussian
  mse: null
unlearning_methods:
  # sanity_check: null
  # ssd:
  #   dampening_constant: 1
  #   selection_weighting: 10
  bad_teacher: null
  # amnesiac: null
batch_size: 256
train_params:
  num_epochs: 3
  learning_rate: 0.1
runs_per_forget_set: 1