batch_size: 256
dataset_params:
  dataset_name: CIFAR10
  forget_set_size: 7000
  forget_sets:
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - random
distinguisher_params:
  kld:
    perturbation_type: gaussian
  mia:
    mia_type: logreg
train_params:
  learning_rate: 0.1
  num_epochs: 200
unlearning_methods:
  ssd:
    dampening_constant: 1
    selection_weighting: 5
